# Generated by Django 2.2.10 on 2020-03-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/article/%Y/%m/%d', verbose_name='文章图片'),
        ),
    ]
