# Generated by Django 2.2.10 on 2020-04-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200330_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(default='游客', max_length=50, verbose_name='昵称'),
        ),
    ]
