# Generated by Django 2.2.10 on 2020-03-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='yunicon',
            field=models.CharField(default='', max_length=200),
        ),
    ]
