# Generated by Django 2.2.10 on 2020-04-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200401_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=30, verbose_name='友链名字')),
                ('link_url', models.CharField(max_length=50, verbose_name='友链网址')),
            ],
            options={
                'verbose_name_plural': '友情链接',
                'verbose_name': '友情链接',
                'db_table': 'friend_link',
            },
        ),
    ]
